### ISSUE TITLE
Twój blog

### ISSUE THREAD

**Issue by Xatoos** [jundymek/jundymek-portfolio#7]
Cześć, czy możesz naprawić komentarze na swoim blogu? Chciałem dodać do artykułu, a niestety nie działa captcha.

**Comment by jundymek** [comment]
Wyłączyłem... ;)

**Comment by Xatoos** [comment]
O kurcze, szkoda.

**Comment by jundymek** [comment]
Captche wyłączyłem żebyś dodał commenta... ;)

**Comment by Xatoos** [comment]
Poszedł, sprawdź proszę

**Comment by Xatoos** [comment]
Inna kwestia, że jak była wyłączona captcha to już nie pamiętam gdzie, ale wyskoczył mi błąd i po tym udało mi się Ciebie zlokalizować tj. po ksywce "jundymek" bo wyskakuje pełna ścieżka katalogu gdzie trzymasz stronę - btw dobrze byłoby to naprawić bo to z kategorii Full Path Disclosure :P. Przemyśl czy nie zostawić jakiegoś kontaktu do siebie bo nie wiem czy inni będą tak uparci w szukaniu, a ja miałem motywację bo mi się stare czasy przypomniały :)

https://owasp.org/www-community/attacks/Full_Path_Disclosure
